### ISSUE TITLE
java.lang.IllegalAccessError in UITestRunner.runIde() method

### ISSUE THREAD

**Issue by richard0202** [redhat-developer/intellij-common-ui-test-library#162]
After calling UITestRunner.runIde() method there is an error.

Steps to reproduce:
1) Clone https://github.com/redhat-developer/intellij-openshift-connector
2) Build project: `./gradlew build`
3) Run Integration UI tests: `./gradlew integrationUITest`
4) There will be popup window "Evaluation License Expired" -> continue with "Ok"
5) Tests will end with the error bellow

The cause of that error is probably outdated Gson library in intellij telemetry plugin (see screen). In error stack trace (GsonRequestBodyConverter.java:46) there is a call of method "newJsonWriter" which is in older versions private, however [in newer version of Gson](https://github.com/google/gson/blob/8c523b8d2c2efe22a670fc63e5369692342f0632/gson/src/main/java/com/google/gson/Gson.java#LL900C1-L900C3) this method is public.

```java
java.lang.IllegalAccessError: class retrofit2.converter.gson.GsonRequestBodyConverter tried to access
private method 'com.google.gson.stream.JsonWriter com.google.gson.Gson.newJsonWriter(java.io.Writer)'
(retrofit2.converter.gson.GsonRequestBodyConverter and com.google.gson.Gson are in unnamed module of loader
'app')
      at retrofit2.converter.gson.GsonRequestBodyConverter.convert(GsonRequestBodyConverter.java:46)
      at retrofit2.converter.gson.GsonRequestBodyConverter.convert(GsonRequestBodyConverter.java:30)
      at retrofit2.ParameterHandler$Body.apply(ParameterHandler.java:429)
      at retrofit2.RequestFactory.create(RequestFactory.java:129)
      at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:208)
      at retrofit2.OkHttpCall.getRawCall(OkHttpCall.java:107)
      at retrofit2.OkHttpCall.execute(OkHttpCall.java:197)
      at com.intellij.remoterobot.client.IdeRobotClient.findAllByXpath(IdeRobotClient.kt:39)
      at com.intellij.remoterobot.search.Finder.findMany(Finder.kt:43)
      at com.intellij.remoterobot.SearchContext$find$1$2.invoke(SearchContext.kt:63)
      at com.intellij.remoterobot.SearchContext$find$1$2.invoke(SearchContext.kt:53)
      at com.intellij.remoterobot.utils.RepeatUtilsKt$waitFor$3.invoke(RepeatUtils.kt:49)
      at com.intellij.remoterobot.utils.RepeatUtilsKt$waitFor$3.invoke(RepeatUtils.kt:49)
      at com.intellij.remoterobot.utils.RepeatUtilsKt.repeatInTime(RepeatUtils.kt:99)
      at com.intellij.remoterobot.utils.RepeatUtilsKt.repeatInTime$default(RepeatUtils.kt:87)
      at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor(RepeatUtils.kt:49)
      at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor$default(RepeatUtils.kt:36)
      at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:53)
      at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:51)
      at com.intellij.remoterobot.stepsProcessing.StepWorkerKt.step(StepWorker.kt:23)
      at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:51)
      at com.intellij.remoterobot.RemoteRobot.find(RemoteRobot.kt:32)
      at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:34)
      at com.intellij.remoterobot.RemoteRobot.find(RemoteRobot.kt:32)
      at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:28)
      at com.intellij.remoterobot.RemoteRobot.find(RemoteRobot.kt:32)
      at com.redhat.devtools.intellij.commonuitest.UITestRunner.lambda$getRemoteRobotConnection$1(UITestRunner.java:150)
      at com.intellij.remoterobot.stepsProcessing.StepWorkerKt.step(StepWorker.kt:23)
      at com.redhat.devtools.intellij.commonuitest.UITestRunner.getRemoteRobotConnection(UITestRunner.java:146)
      at com.redhat.devtools.intellij.commonuitest.UITestRunner.lambda$runIde$0(UITestRunner.java:85)
      at com.intellij.remoterobot.stepsProcessing.StepWorkerKt.step(StepWorker.kt:23)
      at com.redhat.devtools.intellij.commonuitest.UITestRunner.runIde(UITestRunner.java:70)
      at org.jboss.tools.intellij.openshift.test.ui.runner.IdeaRunner.startIDE(IdeaRunner.java:42)
      at org.jboss.tools.intellij.openshift.test.ui.junit.TestRunnerExtension.beforeAll(TestRunnerExtension.java:33)
      at ...
```
![intellij telemetry plugin-outdated-gson](https://github.com/redhat-developer/intellij-common-ui-test-library/assets/75847533/a44a4aa5-9abc-4643-8e9d-f7cc60822453)

**Comment by richard0202** [comment]
Steps to reproduce:
1) Clone https://github.com/redhat-developer/intellij-openshift-connector
2) Build project: `./gradlew build`
3) Run Integration UI tests: `./gradlew integrationUITest`
4) There will be popup window "Evaluation License Expired" -> continue with "Ok"
5) Tests will end with the error above

The cause of that error is probably outdated Gson library in intellij telemetry plugin. In error stacktrace (GsonRequestBodyConverter.java:46) there is a call of method "newJsonWriter" which is in older versions private, however in newer version of Gson this method is public.

**Comment by adietish** [comment]
remote robot is using `retrofit 2.9.0` and gson `2.9.0`
https://github.com/JetBrains/intellij-ui-test-robot/blob/d9892159c4542ff2aca2726937f9b7b3af363122/remote-robot/build.gradle.kts#L13-L14C36
