### ISSUE TITLE
java.net.ConnectException on Windows during the test run

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-common-ui-test-library#95]
- java.net.ConnectException (Failed to connect to /127.0.0.1:8580) during test run, affects test run and test result
- issue seen on WINDOWS only (Windows Server 2019)

- **WORKAROUND**: rerun of the tests

```
Error: Exception in thread "Thread-4" java.net.ConnectException: Failed to connect to /127.0.0.1:8580
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
	at com.intellij.remoterobot.client.IdeRobotClient.execute(IdeRobotClient.kt:63)
	at com.intellij.remoterobot.JavaScriptApi$DefaultImpls.runJs(JavaScriptApi.kt:[57](https://github.com/redhat-developer/intellij-quarkus/runs/5344406140?check_suite_focus=true#step:4:57))
	at com.intellij.remoterobot.RemoteRobot.runJs(RemoteRobot.kt:32)
	at com.intellij.remoterobot.fixtures.Fixture.runJs(Fixture.kt:92)
	at com.intellij.remoterobot.fixtures.Fixture.runJs$default(Fixture.kt:85)
	at com.intellij.remoterobot.fixtures.Fixture.runJs(Fixture.kt)
	at com.redhat.devtools.intellij.commonuitest.UITestRunner.lambda$closeIde$1(UITestRunner.java:100)
	at com.intellij.remoterobot.stepsProcessing.StepWorkerKt$step$1.invoke(StepWorker.kt:16)
	at com.intellij.remoterobot.stepsProcessing.StepWorkerKt$step$1.invoke(StepWorker.kt:15)
	at com.intellij.remoterobot.stepsProcessing.StepWorkerKt.step(StepWorker.kt:23)
	at com.intellij.remoterobot.stepsProcessing.StepWorkerKt.step(StepWorker.kt:15)
	at com.redhat.devtools.intellij.commonuitest.UITestRunner.closeIde(UITestRunner.java:98)
	at org.jboss.tools.intellij.quarkus.tests.AbstractQuarkusTest$CloseIntelliJBeforeQuit.run(AbstractQuarkusTest.java:41)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:615)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
	... 32 more
org.jboss.tools.intellij.quarkus.tests.BasicTest


  Test createBuildQuarkusMavenTest() FAILED (6m 33s)
1 test completed, 1 failed

  com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT10S) for condition function (Failed to find 'Welcome To IntelliJ IDEA Dialog' by 'FlatWelcomeFrame type' in 10s)
      at org.jboss.tools.intellij.quarkus.tests.BasicTest.finishTestRun(BasicTest.java:[58](https://github.com/redhat-developer/intellij-quarkus/runs/5344406140?check_suite_focus=true#step:4:58))
```

**Comment by zcervink** [comment]
Issue fixed by https://github.com/redhat-developer/intellij-common-ui-test-library/pull/97
